// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmTVOgSDsHhzQHVtJtDHfPercc9locis',
    appId: '1:312772265280:web:9d304928fc5ccb2eeaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    authDomain: 'resmory.firebaseapp.com',
    storageBucket: 'resmory.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76vvyC8cBoXVr6CQY62Z62HJ6V-ve3nU',
    appId: '1:312772265280:android:2750d81f800548d1eaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    storageBucket: 'resmory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBEo9QU-7qtguQbGJfEFu9k-EJGYruuMo',
    appId: '1:312772265280:ios:f5fbe40af6ad7ab8eaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    storageBucket: 'resmory.appspot.com',
    iosClientId: '312772265280-bsp9mors6cnih7l05cvm9p75prkqtn5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.resmoryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBEo9QU-7qtguQbGJfEFu9k-EJGYruuMo',
    appId: '1:312772265280:ios:f5fbe40af6ad7ab8eaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    storageBucket: 'resmory.appspot.com',
    iosClientId: '312772265280-bsp9mors6cnih7l05cvm9p75prkqtn5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.resmoryFlutter',
  );
}
