// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmTVOgSDsHhzQHVtJtDHfPercc9locis',
    appId: '1:312772265280:web:9d304928fc5ccb2eeaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    authDomain: 'resmory.firebaseapp.com',
    storageBucket: 'resmory.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76vvyC8cBoXVr6CQY62Z62HJ6V-ve3nU',
    appId: '1:312772265280:android:e6229e333e98e77aeaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    storageBucket: 'resmory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBEo9QU-7qtguQbGJfEFu9k-EJGYruuMo',
    appId: '1:312772265280:ios:57c126efa5c92db6eaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    storageBucket: 'resmory.appspot.com',
    iosClientId: '312772265280-dpf6lgu5t0ivs2i6mi9srngd0263g79v.apps.googleusercontent.com',
    iosBundleId: 'com.blackbear.resmory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBEo9QU-7qtguQbGJfEFu9k-EJGYruuMo',
    appId: '1:312772265280:ios:57c126efa5c92db6eaa6a5',
    messagingSenderId: '312772265280',
    projectId: 'resmory',
    storageBucket: 'resmory.appspot.com',
    iosClientId: '312772265280-dpf6lgu5t0ivs2i6mi9srngd0263g79v.apps.googleusercontent.com',
    iosBundleId: 'com.blackbear.resmory',
  );
}
